#!/bin/bash

echo "=== Arduino Mega ROS2 Komut Testi ==="
echo ""

echo "1. Arduino bridge'i başlatmak için:"
echo "   ros2 run arduino_ros2_hello arduino_bridge"
echo ""

echo "2. Arduino'dan gelen verileri dinlemek için:"
echo "   ros2 topic echo /arduino_status"
echo ""

echo "3. Test komutları:"
echo "   # Aktüatör kontrolü"
echo "   ros2 topic pub /arduino_cmd std_msgs/String 'data: ACTUATOR_EXTEND'"
echo "   ros2 topic pub /arduino_cmd std_msgs/String 'data: ACTUATOR_RETRACT'"
echo "   ros2 topic pub /arduino_cmd std_msgs/String 'data: ACTUATOR_STOP'"
echo ""
echo "   # Direksiyon kontrolü"
echo "   ros2 topic pub /arduino_cmd std_msgs/String 'data: STEER_LEFT'"
echo "   ros2 topic pub /arduino_cmd std_msgs/String 'data: STEER_RIGHT'"
echo ""
echo "   # PWM kontrolü"
echo "   ros2 topic pub /arduino_cmd std_msgs/String 'data: PWM:100'"
echo "   ros2 topic pub /arduino_cmd std_msgs/String 'data: PWM:200'"
echo ""
echo "   # Durum sorgulama"
echo "   ros2 topic pub /arduino_cmd std_msgs/String 'data: GET_STATUS'"
echo ""
echo "   # Otomatik testler"
echo "   ros2 topic pub /arduino_cmd std_msgs/String 'data: TEST_PWM'"
echo "   ros2 topic pub /arduino_cmd std_msgs/String 'data: TEST_STEER'"
echo "   ros2 topic pub /arduino_cmd std_msgs/String 'data: TEST_ACTUATOR'"
echo ""

echo "4. Topic listesini görmek için:"
echo "   ros2 topic list"
echo ""

echo "5. Arduino Mega port kontrolü:"
echo "   ls /dev/ttyACM*"
echo "   ls /dev/ttyUSB*"
echo ""

echo "6. Pin açıklamaları (Arduino Mega):"
echo "   PWM Pin 12: Pot kontrolü (0-255)"
echo "   R_Signal 5: Aktüatör ileri"
echo "   F_Signal 4: Aktüatör geri"
echo "   Switch1 43: Fren sensörü"
echo "   Switch2 41: Fren sensörü"
echo "   Dir 2: Servo yön kontrolü"
echo "   Pulse 7: Servo sinyal"
echo "   Volt 49: Aktüatör güç"
echo ""

echo "Not: Arduino Mega'nın bağlı olduğundan ve doğru porta bağlandığından emin olun!" 