controller_manager:
  ros__parameters:
    update_rate: 100  # Hz

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    ackermann_steering_controller:
      type: ackermann_steering_controller/AckermannSteeringController
      # URDF'deki eklem isimleri
      front_steering_joint_names: ["left_front_steering_joint", "right_front_steering_joint"]
      rear_wheels_joint_names: ["left_back", "right_back"]

      # Robot geometrisi (URDF'den hesaplanan değerler)
      # Dingil mesafesi (ön ve arka tekerlekler arası x eksenindeki mesafe)
      wheelbase: 1.4 # (0.725318 - (-0.674682))
      # Ön tekerlek iz genişliği (ön tekerlekler arası y eksenindeki mesafe)
      front_wheel_track: 1.212299 # (0.705779 + 0.50652)
      # Arka tekerlek iz genişliği
      rear_wheel_track: 1.212299
      # Tekerlek yarıçapı
      wheel_radius: 0.3