slam_toolbox:
  ros__parameters:
    # Plugin params
    solver_plugin: "solver_plugins::CeresSolver"
    ceres_linear_solver: "SPARSE_NORMAL_CHOLESKY"
    ceres_preconditioner: "SCHUR_JACOBI"
    ceres_trust_region_strategy: "LEVENBERG_MARQUARDT"
    ceres_dogleg_type: "TRADITIONAL_DOGLEG"
    ceres_loss_function: "None"

    # ROS Parameters
    odom_frame: "odom"
    map_frame: "map"
    base_frame: "base_footprint"
    scan_topic: "/scan"
    
    # --- Loop Closure & Matching Parameters ---
    # Disable scan matching to rely purely on odometry for frame-to-frame updates
    use_scan_matching: false
    use_scan_barycenter: true
    # Start mapping immediately without waiting for the robot to move
    minimum_travel_distance: 0.0
    minimum_travel_heading: 0.0
    
    # Number of scans to buffer for loop closure. Increased for better long-term memory.
    scan_buffer_size: 100
    
    # Minimum score for a loop closure match. Increased for higher confidence.
    loop_match_minimum_response_fine: 0.8
    
    # Search radius for loop closures.
    loop_search_maximum_distance: 15.0

    # --- Scan Matcher Parameters ---
    # How far to search for a match.
    scan_match_max_linear_distance: 1.0
    scan_match_max_angular_distance: 0.5
    
    # --- Map Update Parameters ---
    map_update_interval: 2.0
    resolution: 0.05
    # Set the minimum laser range to match the sensor's capabilities
    min_laser_range: 0.2
    max_laser_range: 20.0
    
    # Let slam_toolbox publish the map->odom transform
    map_to_odom_publish_period: 0.1

    # --- Timing & Transform Parameters ---
    # How long to buffer transforms (seconds). Increased to handle initial sim startup delays.
    tf_buffer_duration: 2.0

    # General
    use_sim_time: True 